### ISSUE TITLE
No files are showing in the code section, even if I download.

### ISSUE THREAD

**Issue by display5** [MessageLoggerBD/MessageLogger#13]
[MessageLogger-master.zip](https://github.com/MessageLoggerBD/MessageLogger/files/5148833/MessageLogger-master.zip)

**Comment by display5** [comment]
I got my hand on a snapshot now, so here it is:
https://we.tl/t-lCwih7acog
(i needed to use WeTransfer because GitHub doesn't let me)

**Comment by DKMellow21** [comment]
Could you please reupload it?
